# Generated by Django 3.1.5 on 2021-04-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_wallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
