# Generated by Django 3.1.5 on 2021-01-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payday_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
